### ISSUE TITLE
Styling DL.

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/devtools-docs#250]
Pulling from [a comment on a PR](https://github.com/GoogleChrome/devtools-docs/pull/238#issuecomment-74562764) for making tables into DL's we want to make it so appropriate DL's are shown side-by-side. With this I also added in bolding DT's by default and adding a colon in after the term using styling to save us some typing.

The proposed patch is as follows:
```css
dt {
    font-weight: bold;
}

dt:after {
    content: ":";
}

dl.one-to-one dt {
    display: inline;
    margin-right: 2px;
}

dl.one-to-one dd {
    display: inline;
    margin: 0;
}

dl.one-to-one dd:after {
    content:"\A";
    white-space: pre;
}
```

This allows us to mark the definition lists that only have one term to an item with the class `one-to-one`. It will style it to be an inline list look.
![example1](https://cloud.githubusercontent.com/assets/868301/6314443/15d075ac-b9ad-11e4-8d5b-4b9262655baf.png)

There is one current bug in this code which makes the definitions extend beyond the right margin of the article itself. The next image shows a blue box and the red line is just to show the border line more clearly since it is hard to see in the original screenshot.
![problem1](https://cloud.githubusercontent.com/assets/868301/6314454/7afbe844-b9ad-11e4-807c-e211da878aae.png)

So, some more work is needed before this is tossed in. If anyone has any initial feedback though let me know.

**Comment by paulirish** [comment]
I think proper two-column (a la tables) is easier to read.

**Comment by Garbee** [comment]
Yea, having the same space between each term and definition would look best. Looking into it now, however there doesn't seem to be a very good solution that doesn't involve `float`. :frowning:

**Comment by Garbee** [comment]
After quite a bit of messing around... I cheated. Bootstrap ftw.

```css
dt {
    font-weight: bold;
}

dt:after {
    content: ":";
}

dl.one-to-one:before,
dl.one-to-one:after {
    display: table;
    content: " ";
}

dl.one-to-one:after {
    clear:both;
}

dl.one-to-one dt {
    float: left;
    width: 160px;
    overflow: hidden;
    clear: left;
    text-align: right;
    white-space: nowrap;
  }
dl.one-to-one dd {
    margin-left: 180px;
  }

@media(max-width:580px) {
    dl.one-to-one dt {
        width: 100%;
        text-align: left;
    }
    dl.one-to-one dd {
        text-align: left;
        width: 100%;
        margin-left: 0;
    }
}
```

Pulled the dl-horizontal class stuff from there and fixed it up for our needs. Also added a media query to make the terms and definitions on their own line on small devices so they are legible.

This still needs some work for things with multiple terms to a definition, but a good start.
![current_dl](https://cloud.githubusercontent.com/assets/868301/6338174/e52b81ce-bb7a-11e4-8f4f-816a310716f6.png)
